### ISSUE TITLE
Conda installation in a Python 3 environment doesn't work

### ISSUE THREAD

**Issue by khinsen** [MDAnalysis/mdanalysis#1446]
### Expected behaviour

`conda install mdanalysis` should create a working installation of MDAnalysis, or else report an error.

### Actual behaviour

When run in a Python 3 conda environment, `conda install mdanalysis` installs a Python 2 version of MDAnalysis (under `lib/python2.7`). It does not install Python 2, so the installation is unusable.

Note that the installation instructions nowhere mention if MDAnalysis expects Python 2 or Python 3, so it is certainly not unreasonable to try a conda installation for Python 3.

**Comment by kain88-de** [comment]
@khinsen we don't have python 3 packages right now. In fact MDAnalysis only has experimental python 3 support right now. We are working on getting full python 3 support [this summer](https://github.com/MDAnalysis/mdanalysis/projects/3).

Until then you have to install MDAnalysis from pip on python3. But be warned that some things might not work. 

I'm a bit surprised though that conda just installed the python2 package. Did you install from the conda-forge channel?

**Comment by khinsen** [comment]
Yes. I understand that MDAnalysis has incomplete Python 3 support for now (although it takes a while to figure this out). And then it makes sense not to have a Python 3 conda package. But then I expect one of (1) an error message or (2) an automatic installation of Python 2 as a dependency, with a preference for (1).

**Comment by kain88-de** [comment]
Did you install MDAnalysis from the conda-forge channel?

**Comment by kain88-de** [comment]
What does `conda config --show` return for you?

**Comment by orbeckst** [comment]
I can confirm: In an anaconda3 environment, conda will happily install a non-functional MDAnalysis.

```
Package plan for installation in environment /Users/oliver/anaconda3:

The following NEW packages will be INSTALLED:

    biopython:       1.68-np112py35_0
    griddataformats: 0.3.3-py35_0      conda-forge
    hdf4:            4.2.12-0          conda-forge
    joblib:          0.11-py35_0       conda-forge
    libnetcdf:       4.4.1.1-4         conda-forge
    mdanalysis:      0.16.2-np112_0    conda-forge
    mmtf-python:     1.0.7-py35_0      conda-forge
    netcdf4:         1.2.8-np112py35_0 conda-forge
```
However, despite it being installed by conda, it is not importable
```python
Python 3.5.3 |Anaconda 4.4.0 (x86_64)| (default, Mar  6 2017, 12:15:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDAnalysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'MDAnalysis'
>>>
```
and as originally reported, it was installed in *anaconda3/lib/python2.7/site-packages/*
```
ls anaconda3/lib/python2.7/site-packages/
MDAnalysis                       MDAnalysis-0.16.2-py2.7.egg-info
```

@kain88-de , this is my config:

```
conda config --show
```
gives
```
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/r: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
custom_multichannels:
  local: []
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /Users/oliver/anaconda3/envs
  - /Users/oliver/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /Users/oliver/anaconda3/pkgs
  - /Users/oliver/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```

**Comment by orbeckst** [comment]
P.S.: I followed our [quick-install instructions](http://www.mdanalysis.org/pages/installation_quick_start/)
```
conda config --add channels conda-forge
conda install mdanalysis
```

**Comment by khinsen** [comment]
Here is my conda configuration:

```
(root) ~/ $ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/r: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /Users/hinsen/anaconda3/envs
  - /Users/hinsen/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /Users/hinsen/anaconda3/pkgs
  - /Users/hinsen/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```
