### ISSUE TITLE
Long-term solution for import sorting

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#3656]
## Is your feature request related to a problem? ##

As [discussed](https://github.com/MDAnalysis/mdanalysis/pull/3644#issuecomment-1100836585) in #3644 I am always frustrated when I see unsorted imports 🙃. Especially, for a new import, it is not clear where to put it.

## Describe the solution you'd like ##

Run `isort` with options (to be discussed) for the complete repo

```toml
line_length = 80
indent = 4
multi_line_output = 8  # Vertical Hanging Indent Bracket
include_trailing_comma = true
lines_after_imports = 2
known_first_party = "MDAnalysis"
```

and add a command like `isort --verbose --check-only --diff` to the CI.

## Describe alternatives you've considered ##

Leave everything as it is.
