### ISSUE TITLE
conda build for OS X

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#795]
I've produced a preliminary conda build for OS X:

Try this in a clean environment (that doesn't already have any kind of access to MDAnalysis):

```
conda config --add channels treddy
conda config --add channels MDAnalysis
conda install mdanalysis
```

and let me know if you have any issues (it seems to work for me). It is particularly annoying to test this if you work with an environment that already has a source version installed for development, etc. Also, I had to remove the testing from the conda build procedure because of the circular dependency situation -- so running the tests on the Mac conda build would also be helpful.

There's a huge discussion in #751 and elsewhere regarding conda builds that I skimmed through. It looks like scripts are being put in the `maintainer` package path, although mine look a bit different and I don't see a per-architecture breakdown there yet.

**Comment by kain88-de** [comment]
@tylerjereddy can you share the script you have used to generate the build.

> Also, I had to remove the testing from the conda build procedure because of the circular dependency situation

That sounds strange. The installatoin should work. The `build.sh` script is basically the recommended install way for developers.

> I don't see a per-architecture breakdown there yet.

There shouldn't be one. I can't see a reason why the build process should be different between osx and linux right now. Also conda doesn't encourage that.

**Comment by tylerjereddy** [comment]
The objective was simply to perform a [skeleton build](http://conda.pydata.org/docs/build_tutorials/pkgs.html#building-conda-packages-with-conda-skeleton) from pypi and see if it worked. Out of the box, it didn't, so I edited the code until it did. I don't think it is that strange to have problems--it may just be that one or two other os-x things need to be added to the appropriate channel, but if you start from the skeleton it doesn't just work on my machine. Anyway, I just got the ball rolling--feel free to take over.

`meta.yaml`:

```yaml
package:
  name: mdanalysis
  version: "0.14.0"

source:
  fn: MDAnalysis-0.14.0.tar.gz
  url: https://pypi.python.org/packages/source/M/MDAnalysis/MDAnalysis-0.14.0.tar.gz
  md5: 51e62a1df93b4c84957594977acdbdbd
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mdanalysis = mdanalysis:main
    #
    # Would create an entry point called mdanalysis that calls mdanalysis.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.5.0
    - biopython >=1.59
    - networkx >=1.0
    - griddataformats >=0.3.2
    - six >=1.4.0

  run:
    - python
    - numpy >=1.5.0
    - biopython >=1.59
    - networkx >=1.0
    - griddataformats >=0.3.2
    - six >=1.4.0

#test:
#  # Python imports
#  imports:
#    - MDAnalysis
#    - MDAnalysis.analysis
#    - MDAnalysis.analysis.hbonds
#    - MDAnalysis.coordinates
#    - MDAnalysis.coordinates.pdb
#    - MDAnalysis.core
#    - MDAnalysis.lib
#    - MDAnalysis.lib.formats
#    - MDAnalysis.migration
#    - MDAnalysis.migration.fixes
#    - MDAnalysis.selections
#    - MDAnalysis.tests
#    - MDAnalysis.topology
#    - MDAnalysis.topology.tpr
#    - MDAnalysis.visualization
#
#  # commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#
#
#  # You can also put a file called run_test.py in the recipe that will be run
#  # at test time.
#
#  requires:
#    - nose >=1.3.7
#    # Put any additional test requirements here.  For example
#    # - nose

about:
  home: http://www.mdanalysis.org
  license: GNU General Public License (GPL)
  summary: 'An object-oriented toolkit to analyze molecular dynamics trajectories generated by CHARMM, Gromacs, NAMD, LAMMPS, or Amber.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

and `build.sh`:

```sh
#!/bin/bash

$PYTHON setup.py install

# Add more build steps here, if they are necessary.

# See
# http://docs.continuum.io/conda/build.html
# for a list of environment variables that are set during the build process.
```
